exp_name: INDIGO-BM_rules
dataset_name: INDIGO-BM
train_path: data/INDIGO-BM/train-labeled-typed.txt
valid_path: data/INDIGO-BM/valid-labeled-typed.txt

add_constraints: true
add_mask: true
add_rules: true
rule_weight: 1
add_2hop: false

learning_rate: 0.005
weight_decay: 0.00000005
num_layers: 2
num_epochs: 1000
dropout: 0.5
threshold: 0.5
bce_weight: 10

threshold_a: 0.1
threshold_b: 0.4